=== aleksandr-korotkov/xml-service/src/main/resources/products.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="productlist">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="category" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subcategory" maxOccurs="unbounded">
                                <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="product" maxOccurs="unbounded">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="manufacturer"/>
                                                        <xs:element name="model">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:pattern value="[a-zA-Zа-яА-Я]{2}\d{3}"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                        <xs:element name="dateofmanufacture">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:pattern value="\d{2}[-]\d{2}[-]\d{4}"/>
                                                                    <xs:length value="10"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                        <xs:element name="color">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:string">
                                                                    <xs:enumeration value="red"/>
                                                                    <xs:enumeration value="black"/>
                                                                    <xs:enumeration value="blue"/>
                                                                    <xs:enumeration value="green"/>
                                                                    <xs:enumeration value="yellow"/>
                                                                    <xs:enumeration value="purple"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                        <xs:element name="price">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:decimal">
                                                                    <xs:fractionDigits value="2"/>
                                                                    <xs:minExclusive value="0"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                        <xs:element name="count">
                                                            <xs:simpleType>
                                                                <xs:restriction base="xs:decimal">
                                                                    <xs:minExclusive value="0"/>
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    <xs:attribute name="name" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aleksandr-korotkov/xml-service/src/main/resources/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<productlist
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="products.xsd">
    <category name="метизы">
        <subcategory name="гвозди">
            <product>
                <manufacturer>365days</manufacturer>
                <model>Ab123</model>
                <dateofmanufacture>31-01-2019</dateofmanufacture>
                <color>green</color>
                <price>6.10</price>
                <count>24</count>
            </product>
        </subcategory>
        <subcategory name="саморезы">
            <product>
                <manufacturer>mitsubishi motors</manufacturer>
                <model>se333</model>
                <dateofmanufacture>28-02-2019</dateofmanufacture>
                <color>red</color>
                <price>99.99</price>
                <count>9000</count>
            </product>
        </subcategory>
    </category>
    <category name="электроинструмент">
        <subcategory name="перфораторы">
            <product>
                <manufacturer>bosch</manufacturer>
                <model>xx999</model>
                <dateofmanufacture>22-11-2019</dateofmanufacture>
                <color>black</color>
                <price>999.10</price>
                <count>1</count>
            </product>
        </subcategory>
    </category>
</productlist>
